global_costmap:


  global_frame: /map
  robot_base_frame: /base_footprint #/base_link
  update_frequency: 0.01 #1.0
  static_map: true 

  publish_frequency: 0.5
  resolution: 0.02 # The one of the map
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}