local_costmap:

  global_frame: odom
  robot_base_frame: /base_footprint #/base_link
  update_frequency: 1.0 #5.0
  static_map: false

  publish_frequency: 2.0
  width: 6.0 
  height: 6.0
  rolling_window: true
  resolution: 0.02 # It has to be small
  plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}